apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
data:
  RETAIL_UI_ENDPOINTS_CATALOG: {{ .Values.endpoints.catalog }}
  RETAIL_UI_ENDPOINTS_CARTS: {{ .Values.endpoints.carts }}
  RETAIL_UI_ENDPOINTS_CHECKOUT: {{ .Values.endpoints.checkout }}
  RETAIL_UI_ENDPOINTS_ORDERS: {{ .Values.endpoints.orders }}
